---
title: "publications"
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

makLab members are <b>bolded</b>

<!-- <div class="expand collapsed" data-toggle="collapse" data-target="#uniqueID" aria-expanded="false" aria-controls="uniqueID"> -->
<!-- This section will trigger the appearance of the other section -->
<!-- </div> -->

<!-- <div class="collapsed" id="uniqueID"> -->
<!-- This section will appear and disappear.  -->
<!-- </div> -->

<div class="expand collapsed" data-toggle="collapse" data-target="#2019" aria-expanded="false" aria-controls="2019">
### 2019 <i class="fa fa-angle-double-down"></i>
</div>

<div class="collapse" id="2019">

<!-- <div class="expand collapsed" data-toggle="collapse" data-target="#2019pp" aria-expanded="false" aria-controls="2019pp"> -->
<!-- #### peer-reviewed -->
<!-- </div> -->

<!-- <div class="collapse" id="2019pp"> -->


<b>Gibson EA</b><sup><span>&#8224;</span></sup>, <b>N<span>&#250;</span><span>&#241;</span>ez Y</b><sup><span>&#8224;</span></sup>, Abuawad A, Zota AR, Renzetti S, Devick KL, Gennings C, Golsmith J, Coull BA, <b>Kioumourtzoglou M-A</b>, "An Overview of Methods to Address Distinct Research Questions on Environmental Mixtures: An Application to Persistent Organic Pollutants and Leukocyte Telomere Length", Environmental Health, In Press, 2019 <br>
<small><sup><span>&#8224;</span></sup>The authors contributed equally</small>


Choirat C, Braun D, <b>Kioumourtzoglou M-A</b>, "Data Science in Environmental Health Research", Current Epidemiology Reports, In Press, 2019 [[Link](https://link.springer.com/article/10.1007/s40471-019-00205-5)]


Jin X, Fiore AM, Civerolo K, Bi J, Liu Y, van Donkelaar A, Martin RV, Al-Hamdan M, Zhang Y, Insaf TZ, <b>Kioumourtzoglou M-A</b>, <b>He MZ</b>, Kinney PL. "Comparison of multiple PM<sub>2.5</sub> exposure products for estimating health benefits of emission controls over New York State, USA", Environmental Research Letters, 14 084023, 2019 [[Link](https://iopscience.iop.org/article/10.1088/1748-9326/ab2dcb)]


Westervelt DM, Ma CT, <b>He MZ</b>, Fiore AM, Kinney PL, <b>Kioumourtzoglou M-A</b>, Wang S, Xing J, Ding D, Correa G, "Mid-21st century ozone air quality and health burden in China under emissions scenarios and climate change", Environmental Research Letters, 14 074030, 2019 [[Link](https://iopscience.iop.org/article/10.1088/1748-9326/ab260b)]


Papadogeorgou G, <b>Kioumourtzoglou M-A</b>, Braun D, Zanobetti A, "Low levels of air pollution and health: Effect estimates, methodological challenges and future directions", Current Environmental Health Reports, In Press, 2019 [[Link](https://www.ncbi.nlm.nih.gov/pubmed/31090042)]


<b>Gibson EA</b>, Goldsmith J, <b>Kioumourtzoglou M-A</b>, "Complex Mixtures, Complex Analyses: an Emphasis on Interpretable Results." Current Environmental Health Reports, In Press, 2019


Fry D, <b>Kioumourtzoglou M-A</b>, Treat CA, Burke K, Evans D, Tabb LP, Carrion D, Perera FP, Lovasi GS, "Development and validation of a method to quantify benefits of clean-air taxi legislation." Journal of exposure science & environmental epidemiology, In Press, 2019


Domingo-Relloso A, Grau-Perez M, Martin-Escudero JC, Briongos-Figuero L, Gomez-Ariza JL, Garcia-Barrera T, Dueñas-Laita A, Bobb JF, Chaves J, <b>Kioumourtzoglou M-A</b>, Navas-Acien A, Redon-Mas J, Tellez-Plaza M, "The association of urine metals and metal mixtures with cardiovascular incidence in an adult population from Spain: the Hortega Follow-Up Study." International Journal of Epidemiology, In Press, 2019


Hilpert M, Johnson M, <b>Kioumourtzoglou M-A</b>, Domingo-Relloso A, Peters A, Adria-Mora B, Hernández D, Ross J, Chillrud SA, "A new approach for inferring traffic-related air pollution use of radar-calibrated crowd-sourced traffic data", Environment International, 127:142-159, 2019


McGee G, Weisskopf MG, <b>Kioumourtzoglou M-A</b>, Coull BA, Haneuse S, "Informatively empty clusters with application to multigenerational studies", Biostatistics, In Press, 2019


Gao X, Colicino E, Shen J, <b>Kioumourtzoglou M-A</b>, Just AC, Nwanaji-Enwerem J, Coull BA, Lin X, Vokonas P, Zheng Y, Hou L, Schwartz J, Baccarelli A, "Impacts of air pollution, temperature, and relative humidity on leukocyte distribution: an epigenetic perspective", Environment International, 126:395-405, 2019 


<b>Singh J</b>, Mumford SL, Pollack AZ, Schisterman EF, Weisskopf MG, Navas-Acien A, <b>Kioumourtzoglou M-A</b>, "Tampon Use, Environmental Chemicals and Oxidative Stress in the BioCycle Study", Environmental Health, 18 (11), 2019


Liew Z, <b>Kioumourtzoglou M-A</b>, Roberts AL, O'Reilly <span>&#201;</span>J, Ascherio A, Weisskopf MG, "Negative control exposure analysis to evaluate confounding: an example of acetaminophen exposure and ADHD in the Nurses' Health Study", American Journal of Epidemiology, 188(4):768-775, 2019


Wu X, Braun D, <b>Kioumourtzoglou M-A</b>, Choirat C, Di Q, Dominici F. "Causal inference in the context of an error prone exposure: Air pollution and mortality", Annals of Applied Statistics, 13(1):520-547, 2019

<!-- </div> -->

<!-- <div class="expand collapsed" data-toggle="collapse" data-target="#2019aa" aria-expanded="false" aria-controls="2019aa"> -->
<!-- #### arxiv -->
<!-- </div> -->

<!-- <div class="collapse" id="2019aa"> -->

<!-- empty for now -->

<!-- </div> -->

</div>

<div class="expand collapsed" data-toggle="collapse" data-target="#2018" aria-expanded="false" aria-controls="2018">
### 2018 <i class="fa fa-angle-double-down"></i>
</div>

<div class="collapse" id="2018">


Taylor KM, <b>Kioumourtzoglou M-A</b>, Clover J, Coull BA, Dennerlein JT, Bellinger DC, Weisskopf MG. "Concussion History and Cognitive Function in a Large Cohort of Adolescent Athletes", The American Journal of Sports Medicine, 46(13):3262-3270, 2018


Kupsco A, <b>Kioumourtzoglou M-A</b>, Just AC, Amarasiriwardena C, Estrada-Gutierrez G, Cantoral A, et al. "Analysis of prenatal metals status and childhood cardio-metabolic risk using Bayesian Kernel Machine Regression (BKMR) to assess mixture and interaction effects", Epidemiology, 30(2):263-273, 2018


Raz R, <b>Kioumourtzoglou M-A</b>, Weisskopf MG. "Live Birth Bias and Observed Associations between Air Pollution and Autism", American Journal of Epidemiology, 187(11):2292-2296, 2018 <br>
<small>*Selected as one of the 10 best 2018 AJE Articles of the Year</small>


Wurth R, <b>Kioumourtzoglou M-A</b>, Tucker K, Griffith J, Manjourides J, Suh HH. "Fine Particle Sources and Cognitive Function in an Older Puerto Rican Cohort in Boston", Environmental Epidemiology, 2(3):e022, 2018


<b>Kioumourtzoglou M-A</b><sup><span>&#8224;</span></sup>, Raz R<sup><span>&#8224;</span></sup>, Wilson A, Fluss R, Nirel R, Broday DM, Yuval, Hacker MR, McElrath TF, Grotto I, Koutrakis P, Weisskopf MG. "Traffic-related air pollution and pregnancy loss", Epidemiology, 30(1):4-10, 2018 <br>
<small><sup><span>&#8224;</span></sup>The authors contributed equally</small>


Dickerson AS, Hansen J, <b>Kioumourtzoglou M-A</b>, Specht AJ, Gredal O, Weisskopf MG. "Study of occupation and amyotrophic lateral sclerosis in a Danish cohort", Occup Environ Med, 75(9):630-638, 2018


Wasserman GA, Liu X, Parvez F, Chen Y, Factor-Litvak P, Loiacono NJ, Levy D, Shahriar H, Uddin MN, Islam T, Lomax A, Saxena R, Gibson EA, <b>Kioumourtzoglou M-A</b>, Balac O, et al., "A cross-sectional study of water arsenic exposure and intellectual function in adolescence in Araihazar, Bangladesh", Environment International, 118:304-313, 2018


<b>Kioumourtzoglou M-A</b>, Coull BA, O'Reilly <span>&#201;M/span>J, Ascherio A, Weisskopf MG, "Association of Exposure to Diethylstilbestrol During Pregnancy with Multigenerational Neurodevelopmental Deficits", JAMA Pediatrics, 172(7):670-677, 2018 <br>
<small>*Selected as paper of the month by NIEHS Environmental Factor</small>


Ananth CV, <b>Kioumourtzoglou M-A</b>, Huang Y, Ross Z, Friedman AM, Williams MA, Wang S, Mittleman MA, Schwartz J, "Exposures to Air Pollution and Risk of Placental Abruption of Acute Onset: A Case-Crossover Study of Births in New York City", Epidemiology, 29(5):631-638, 2018

</div>

<div class="expand collapsed" data-toggle="collapse" data-target="#2017" aria-expanded="false" aria-controls="2017">
### 2017 <i class="fa fa-angle-double-down"></i>
</div>

<div class="collapse" id="2017">


Achilleos S, <b>Kioumourtzoglou M-A</b>, Wu C-D, Schwartz JD, Koutrakis P, Papatheodorou S, "Acute Effects of Fine Particulate Matter Constituents on Mortality: A Systematic Review and Meta-regression Analysis", Environment International, 109:89-100, 2017


Seals RM, <b>Kioumourtzoglou M-A</b>, Gredal O, Hansen J, Weisskopf MG, "Occupational Formaldehyde and ALS", European Journal of Epidemiology, 32(10): 893-898, 2017


James P, <b>Kioumourtzoglou M-A</b>, Hart JE, Banay RF, Kloog I, Laden F, "Interrelationships between Walkability, Air Pollution, Greenness, and Body Mass Index", Epidemiology, 28(6): 780-788, 2017


<b>Kioumourtzoglou M-A</b>, Power MC, Hart JE, Okereke OI, Coull BA, Laden F, Weisskopf MG, "The association between air pollution and depression onset among middle-aged and older women", American Journal of Epidemiology, 185(9):801-809, 2017

</div>

<div class="expand collapsed" data-toggle="collapse" data-target="#1arxiv" aria-expanded="false" aria-controls="1arxiv">
### arXiv <i class="fa fa-angle-double-down"></i>
</div>

<div class="collapse" id="1arxiv">

Liu JZ, Paisley J, <b>Kioumourtzoglou M-A</b>, Coull BA, "Adaptive ensemble learning of spatiotemporal processes with calibrated predictive uncertainty: a Bayesian nonparametric approach", arXiv:1904.00521 

Wu X, Mealli F, <b>Kioumourtzoglou M-A</b>, Dominici F, Braun D, "Matching on generalized propensity scores with continuous exposures", arXiv:1812.06575

Liu JZ, Paisley J, <b>Kioumourtzoglou M-A</b>, Coull BA, "Adaptive and calibrated ensemble learning with dependent tail-free process", arXiv:1812.03350

Wu X, Braun D, <b>Kioumourtzoglou M-A</b>, Choirat C, Di Q, Dominici F, "Causal inference in the context of an error prone exposure: Air pollution and Mortality", arXiv:1712.00642


</div>


<div class="expand collapsed" data-toggle="collapse" data-target="#1edit" aria-expanded="false" aria-controls="1edit">
### editorials <i class="fa fa-angle-double-down"></i>
</div>

<div class="collapse" id="1edit">

<b>Kioumourtzoglou M-A</b>, "Identifying Modifiable Risk Factors of Mental Disorders: The Importance of Urban Environmental Exposures", JAMA Psychiatry, Epub ahead of print, 2019

</div>